Description = Image Description
Aperture = F Number
CaptureDate = Create Date
ColorSpace = Color Space
Compression = Compression
Copyright = Copyright
#CopyrightUrl
WhiteBalance = White Balance
DigitalZoom = Digital Zoom Ratio
ExifVersion = Exif Version
ExposureBias = Exposure Compensation
ExposureProgram = Exposure Program
ExposureTime = Exposure Time
Flash = Flash
FocalLength = Focal Length
GpsTimeStamp = GPS Time Stamp
Height = Image Height
IsoSpeedRating = ISO
# Label
Latitude = GPS Latitude
LightSource = Light Source
Longitude = GPS Longitude
Maker = Make
MediaType = MIME Type
MeteringMode = Metering Mode
Model = Camera Model Name
#Rating
#Resolution
#SampleColor
#SensingMethod
Software = Exif Version
#SourceUrl
UsageRights = Rights
ViewRotation = Orientation
Width = Image Width
LensID = Lens Type
LensSpec = Lens
Keywords = Keywords
#Tags
Headline = Headline
Category = Category
Source = Source
#Instructions
#Scene
Creator = Creator
JobTitle = Job Ref Name
#Address
City = City
State = State
#PostalCode
Country = Country
#Phone
#Email
Website = Web Statement
Title = Title
Subject = Subject
#RatingPercent
Comment = User Comment
Author = Artist
SubsetTimeOriginal = Sub Sec Time Original 

XResolution = X Resolution
YResolution = Y Resolution
ResolutionUnit = Resolution Unit
SubjectDistance = Hyperfocal Distance
FocalLenghtIn35mm = Focal Length In 35mm Format
WhiteBalance = White Balance
SceneCaptureType = Scene Capture Type
Contrast = Contrast
Saturation = Saturation
Sharpness = Sharpness
BrightnessValue = Brightness Value

SubjectDistanceRange = Hyperfocal Distance
MaxAperture = Max Aperture Value
BitsPerSample = Bits Per Sample
CompressedBitsPerPixel = Compressed Bits Per Pixel
FlashEnergy = Flash Level
PhotometricInterpretation = PhotometricInterpretation
#Location
#Version
#EditorSoftware
#VersionPath
#Event
