pandoc -s ABOUT-Administrative-configuration-tool.md -o ABOUT-Administrative-configuration-tool.html
pandoc -s ABOUT-prints-this-version-information.md -o ABOUT-prints-this-version-information.html
pandoc -s Administrative-Housekeeping-Reference.md -o Administrative-Housekeeping-Reference.html
pandoc -s ALLOW-Which-image-file-extensions-into-the-archive.md -o ALLOW-Which-image-file-extensions-into-the-archive.html
pandoc -s ARCHIVE-Archives-the-repositories-to-long-term-storage.md -o ARCHIVE-Archives-the-repositories-to-long-term-storage.html
pandoc -s BACKUP-Cold-Backup-the-repositories-to-long-term-storage.md -o BACKUP-Cold-Backup-the-repositories-to-long-term-storage.html
pandoc -s CHECKIN-Checkin-images-from-workspace-into-the-archive.md -o CHECKIN-Checkin-images-from-workspace-into-the-archive.html
pandoc -s CHECKOUT-Checkout-i0mages-from-archive-to-workspace.md -o CHECKOUT-Checkout-i0mages-from-archive-to-workspace.html
pandoc -s Command-line-client-reference.md -o Command-line-client-reference.html
pandoc -s Command-Reference.md -o Command-Reference.html
pandoc -s Config-Cloud-Backup.md -o Config-Cloud-Backup.html
pandoc -s CONFIG-Configures-the-ImgArchive-environment.md -o CONFIG-Configures-the-ImgArchive-environment.html
pandoc -s Config-Exiftool.md -o Config-Exiftool.html
pandoc -s Config-General.md -o Config-General.html
pandoc -s Config-Image-rename.md -o Config-Image-rename.html
pandoc -s Config-Network.md -o Config-Network.html
pandoc -s Config-Template.md -o Config-Template.html
pandoc -s Configuration-Reference.md -o Configuration-Reference.html
pandoc -s DELETE-Delete-images-in-the-archive.md -o DELETE-Delete-images-in-the-archive.html
pandoc -s EXIF.md -o EXIF.html
pandoc -s EXPORT-Export-images-from-archive-into-a-destination-folder.md -o EXPORT-Export-images-from-archive-into-a-destination-folder.html
pandoc -s General-arguments.md -o General-arguments.html
pandoc -s GET-Get-images-from-archive-to-User-Spaces.md -o GET-Get-images-from-archive-to-User-Spaces.html
pandoc -s HELP-On-Administrative-Housekeeping-commands.md -o HELP-On-Administrative-Housekeeping-commands.html
pandoc -s HELP-On-ImgArchive-client.md -o HELP-On-ImgArchive-client.html
pandoc -s HISTORY-Shows-the-check-in-status-history-for-the-archive.md -o HISTORY-Shows-the-check-in-status-history-for-the-archive.html
pandoc -s IMPORT-import-new-images-to-the-archivet.md -o IMPORT-import-new-images-to-the-archivet.html
pandoc -s INIT-Initialises-the-ImgArchive-environment.md -o INIT-Initialises-the-ImgArchive-environment.html
pandoc -s JOURNAL-Displays-the-contents-of-a-journal.md -o JOURNAL-Displays-the-contents-of-a-journal.html
pandoc -s LOG-Show-logs.md -o LOG-Show-logs.html
pandoc -s METADATA-Show-Metadata-properties.md -o METADATA-Show-Metadata-properties.html
pandoc -s Metadata.md -o Metadata.html
pandoc -s NAMING-File-Naming-Convention.md -o NAMING-File-Naming-Convention.html
pandoc -s PROP-Manage-image-properties.md -o PROP-Manage-image-properties.html
pandoc -s PURGE-Purges-deleted-images-from-archive.md -o PURGE-Purges-deleted-images-from-archive.html
pandoc -s Reference-Manual.md -o Reference-Manual.html
pandoc -s Remote-Backup-tool-reference.md -o Remote-Backup-tool-reference.html
pandoc -s SCAN-Scan-the-file-system-for-images-that-can-be-imported-into-the-archive.md -o SCAN-Scan-the-file-system-for-images-that-can-be-imported-into-the-archive.html
pandoc -s Sets-environment-variables.md -o Sets-environment-variables.html
pandoc -s SHOW-Show-details.md -o SHOW-Show-details.html
pandoc -s SHOW-Shows-the-configuration-ImgArchive.md -o SHOW-Shows-the-configuration-ImgArchive.html
pandoc -s STATUS-shows-the-check-inout-status-for-the-images-selected.md -o STATUS-shows-the-check-inout-status-for-the-images-selected.html
pandoc -s SYNC-Synchronises-the-repositories-with-the-associated-backups.md -o SYNC-Synchronises-the-repositories-with-the-associated-backups.html
pandoc -s TEMPLATE-Manage-metadata-templates.md -o TEMPLATE-Manage-metadata-templates.html
pandoc -s The-Image-Archive.md -o The-Image-Archive.html
pandoc -s Tool-Reference.md -o Tool-Reference.html
pandoc -s UNCHECKOUT-Un-checkout-images-from-workspace-into-the-archive.md -o UNCHECKOUT-Un-checkout-images-from-workspace-into-the-archive.html
pandoc -s UNDELETE-Undelete-images-in-the-archive.md -o UNDELETE-Undelete-images-in-the-archive.html
pandoc -s VALIDATE-Validates-the-archive-for-correctness.md -o VALIDATE-Validates-the-archive-for-correctness.html
